// src/codegen/llvm_backend.c
#include "codegen/llvm_backend.h"
#include "semantic/types.h"
#include <stdio.h>

static const char* type_to_llvm(Type* type) {
    if (!type) return "void";
    if (type->kind == TYPE_INT && type->integer.bits == 32) return "i32";
    if (type->kind == TYPE_FLOAT && type->floating.bits == 64) return "double";
    if (type->kind == TYPE_POINTER) return "ptr";
    return "i32"; // Заглушка
}

static void llvm_print_value(FILE* out, IRValue* val) {
    if (!val) { fprintf(out, "null"); return; }
    if (val->kind == IR_VALUE_CONST_INT) fprintf(out, "%lld", val->int_val);
    else if (val->kind == IR_VALUE_CONST_FLOAT) fprintf(out, "%f", val->float_val);
    else fprintf(out, "%.*s", (int)val->name.length, val->name.data);
}

static void llvm_emit_instruction(FILE* out, IRInstruction* instr) {
    fprintf(out, "  ");
    if (instr->result) {
        llvm_print_value(out, instr->result);
        fprintf(out, " = ");
    }
    
    switch (instr->opcode) {
        case IR_OP_ASSIGN: 
            llvm_print_value(out, instr->operand1); 
            fprintf(out, "\n"); 
            break;
        case IR_OP_ADD: fprintf(out, "add "); break;
        case IR_OP_SUB: fprintf(out, "sub "); break;
        case IR_OP_MUL: fprintf(out, "mul "); break;
        case IR_OP_DIV: fprintf(out, "fdiv "); break; // упрощенно
        case IR_OP_RETURN: 
            fprintf(out, "ret "); 
            llvm_print_value(out, instr->operand1); 
            fprintf(out, "\n"); 
            return;
        default: fprintf(out, "call/other\n"); break;
    }
    
    if (instr->opcode >= IR_OP_ADD && instr->opcode <= IR_OP_DIV) {
        fprintf(out, "i32 "); // Упрощенно для демо
        llvm_print_value(out, instr->operand1);
        fprintf(out, ", ");
        llvm_print_value(out, instr->operand2);
        fprintf(out, "\n");
    }
}

void llvm_backend_generate(FILE* out, IRModule* module, Arena* arena) {
    (void)arena;
    fprintf(out, "; Generated by Bevel Compiler (LLVM IR Backend)\n\n");
    
    for (IRFunction* func = module->functions; func; func = func->next) {
        fprintf(out, "define %s @%.*s(", type_to_llvm(func->return_type), 
                (int)func->name.length, func->name.data);
        
        for (int i = 0; i < func->param_count; i++) {
            if (i > 0) fprintf(out, ", ");
            fprintf(out, "%s %%arg%d", type_to_llvm(func->params[i]->type), i);
        }
        fprintf(out, ") {\n");
        
        if (func->blocks) {
            fprintf(out, "entry:\n");
            for (IRInstruction* instr = func->blocks->instructions; instr; instr = instr->next) {
                llvm_emit_instruction(out, instr);
            }
        }
        fprintf(out, "}\n\n");
    }
}