// src/codegen/x86_backend.c
#include "codegen/x86_backend.h"
#include <stdio.h>

void x86_backend_generate(FILE* out, IRModule* module, Arena* arena) {
    (void)module;
    (void)arena;
    fprintf(out, "# x86_64 Assembly Backend (Under Construction)\n");
    fprintf(out, "# Generated by Bevel Compiler\n\n");
    fprintf(out, "    .global main\n");
    fprintf(out, "    .text\n");
    fprintf(out, "main:\n");
    fprintf(out, "    mov $0, %%eax\n");
    fprintf(out, "    ret\n");
}